### ISSUE TITLE
file pathをコマンドまたはボタンによって更新したい

### ISSUE THREAD

**Issue by wp041** [L7Cy/obsidian-dynamic-timetable#1]
dynamic timetable、非常に便利に使わせて頂いております。
機能についての要望を一つ投稿させて下さい。

file pathをコマンドまたはボタンによって更新したいです。

私は普段、タスクをデイリーノートで管理するのですが、日にちが変わる際にdynamic timetableが参照するfile pathを毎回`show/hide timetable`コマンドを2回押すことによって更新しています。この作業が1コマンドで済めばなと思い投稿させていただきました。そのような実装はお考えでしょうか？

**Comment by L7Cy** [comment]
参照するfile pathを変更するためのコマンドを追加するよりも，デイリーノートのフォルダへのpathや正規表現などを指定することで，参照するfile pathが自動で切り替わるようにするのがよいのではないかと思うのですが，どうでしょうか？

**Comment by wp041** [comment]
なるほど。
しかし、私のユースケースとして日を超えて数時間は前の日にちのタスクを引き継いで使い、寝る直前に切り替えるという方法なのです。そのために手動で切り替える方法もあるとありがたいと思い、上記のような投稿になりました。

**Comment by L7Cy** [comment]
確かにそれなら手動で切り替えられるほうが良さそうですね．近いうちにfile pathを更新するコマンドを追加しようと思います．
