### ISSUE TITLE
Estimated timeの時間指定から:を省きたい

### ISSUE THREAD

**Issue by wp041** [L7Cy/obsidian-dynamic-timetable#2]
@を使い、Estimated timeを設定する際に:を入力するのが大変なため、@12:34=@1234といったような入力でも認識するようにしたいです。

**Comment by wp041** [comment]
実装ありがとうございます！
バグ報告です
timetableタブで:つきの時間の文字列は表示されないですが、短縮形のそれは文字列が表示されてしまいます

![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/114465138/cfc931f9-5c03-4cb5-9b44-ec38c1caf8eb)
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/114465138/bac0e6c2-df77-402b-9490-f640e602e855)

といった感じです

**Comment by L7Cy** [comment]
報告ありがとうございます．修正しました．
