### ISSUE TITLE
buffer time の表示がおかしい

### ISSUE THREAD

**Issue by wp041** [L7Cy/obsidian-dynamic-timetable#4]
buffer timeが2日分（2880分）余分に表示されてしまう

↓の画像のような形です
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/114465138/43caa26d-e8fb-49e5-8f2a-8bcbf93f8c12)

また、そのようなバグが起きない時間指定タスクもあり、私ではバグの発生条件を突き止めることができませんでした。

**Comment by L7Cy** [comment]
おそらく，新しく追加したDate Delimiterが原因だと思われます．2.0.5にアップデートして，Date Delimiterの値を削除し，動作を確認してみてください．

**Comment by wp041** [comment]
治りました！ありがとうございます
