### ISSUE TITLE
Excluding tasks messes the timetable

### ISSUE THREAD

**Issue by Mixpap** [L7Cy/obsidian-dynamic-timetable#6]
As the title says, I use the timetable as a ...timetable, but I keep the tasks unchecked because it messes the timetable. The first unchecked task forgets the tasks before it and uses the current time a start time.

**Comment by L7Cy** [comment]
What do you mean by that? Are you saying that when you check a task, you don't want that task to be excluded from the timetable?

**Comment by Mixpap** [comment]
It can be excluded but not reset the whole timetable. 
For example, in this situation:
 [] starting task ; @09:00 ; 60 
 [] second task ; 60
 [] third task ; 60
 ...
 you can plan a whole day. 
 Task three is assigned at 11:00-12:00
 but by checking the starting task  at a time not **exactly** 10:00 the timetable resets and assigns the second, third etc based on the current time. 
I don't know if this is by design, but I think it would be better if the tasks should be seen in the rendered timetable just as in the source file, striked out or with a tick or something similar. Based on this you can also observe gaps (tasks in the middle that are not finished) and would be simpler to comprehend.

Also, thanks for your plugin, 
I find it the simplest and most valuable task plugin I use.

**Comment by L7Cy** [comment]
I've implemented a feature to manage completed tasks. Could you please check if this meets your needs?

**Comment by Mixpap** [comment]
Thanks, L7Cy.
Seems much better, but I think there is still a bug:
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/10127931/de425183-050c-4b51-be5c-d441cca1f6a7)
renders to
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/10127931/8f757a3f-a4f8-4126-87a0-d66e79d4bf7a)
where it should task0 be starting from 10.30.

However it works if the task0 is checked
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/10127931/1bcf4375-b896-433d-b17c-085e33e583c7)

**Comment by L7Cy** [comment]
The start time set for the topmost uncompleted task is designed to be ignored. Therefore, the behavior you see in the second image is the correct function of the plugin.
The reason you're seeing what's in the third image is because you haven't executed the "Complete Task" command (or button). This command simultaneously checks the checkbox and rewrites the estimated time and scheduled start time to the actual values.

**Comment by L7Cy** [comment]
I noticed that there was an issue with the start times not matching the completed times.
I've fundamentally changed the way the timetable is calculated. With the latest update, I think it should work fine now.
[![Image from Gyazo](https://i.gyazo.com/24399ecd94fec57a6fee071742ef93de.png)](https://gyazo.com/24399ecd94fec57a6fee071742ef93de)
[![Image from Gyazo](https://i.gyazo.com/a6c9e2ec30c2cee01651b2bfb62c0e11.png)](https://gyazo.com/a6c9e2ec30c2cee01651b2bfb62c0e11)

**Comment by Mixpap** [comment]
Ok now I think I understand it, seems very good.
Thanks!
