### ISSUE TITLE
start timeが勝手に設定される

### ISSUE THREAD

**Issue by wp041** [L7Cy/obsidian-dynamic-timetable#7]
## 背景
しばらくv3.0.1を使用し、最近最新版に更新しました

## 概要
設定してもいないstart timeが勝手に設定されてしまいます

## 詳細
下記のような状態では
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/114465138/f84bae77-acdd-4d52-913c-00bd08cea3a0)
正常に動作します。
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/114465138/70705c28-5677-46be-a6ef-2b5c69c0539d)

しかし、タスクaaaをコンプリートすると、
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/114465138/aea14eb2-5aa7-425f-ac94-a92e2bbddd6c)
- cccのstart timeが勝手に設定される
- bのestimate timeが反映されない
という症状が発生します
![image](https://github.com/L7Cy/obsidian-dynamic-timetable/assets/114465138/0abc398b-a250-49d6-8737-39f8dbdc454c)

**Comment by L7Cy** [comment]
最新版では，同期の関係で[プラグインの専用コマンド](https://github.com/L7Cy/obsidian-dynamic-timetable#task-completion-and-interruption)でのみ反映されるようになっています．現時点では，ファイルを直接編集して完了させる方法では反映されないので，これらのコマンドやボタンを使ってください．

**Comment by wp041** [comment]
なるほど、ありがとうございます！
